import 'package:flutter/material.dart';

class DetailPage extends StatelessWidget {
  final int index;

  DetailPage(this.index);

  List<String> listaMapHinos = [
    'SANTO, SANTO, SANTO!',
    'Ó ADORAI O SENHOR',
    'O DEUS ETERNO REINA',
    'LOUVOR AO TRINO DEUS',
    'JUBILOSOS TE ADORAMOS',
    'NÓS TE ADORAMOS',
    'SEJAS LOUVADO',
    'Ó DEUS DE AMOR',
    'SANTO, SANTO, PAI BONDOSO',
    'O SENHOR ESTÁ AQUI',
    'MAIOR QUE TUDO',
    'VINDE, POVO DO SENHOR',
    'LOUVAMOS-TE, Ó DEUS',
    'LOUVEMOS O REI',
    'TU ÉS FIEL, SENHOR',
    'SUBLIME AMOR',
    'DEUS É NOSSO PAI AMADO',
    'DEUS É NOSSO PAI CELESTE',
    'A DEUS DEMOS GLÓRIAS',
    'GRANDE É O SENHOR',
    'EU TE AMO, Ó DEUS',
    'A TI TODA GLÓRIA',
    'LOUVAI A CRISTO',
    'REI DOS REIS',
    'JESUS, SEMPRE TE AMO',
    'SAUDAI O NOME DE JESUS',
    'COM GLÓRIA COROAI',
    'LINDO ÉS, MEU MESTRE',
    'O AMOR DE JESUS',
    'SEMPRE VENCENDO',
    'JESUS, TU ÉS A MINHA VIDA',
    'BRILHA, JESUS',
    'A ESPERANÇA É JESUS',
    'PRECIOSO NOME',
    'ELE É EXALTADO',
    'POR SEU IMENSO AMOR',
    'CRISTO',
    'A TI RENDEMOS GLÓRIA',
    'GLÓRIAS AO REI DE AMOR',
    'CONCEDE-NOS O ESPÍRITO',
    'CHUVAS DE BÊNÇÃOS',
    'VEM, SANTO ESPÍRITO, AGORA',
    'O SANTO ESPÍRITO',
    'SUAVE ESPÍRITO',
    'DIA DE CHUVA',
    'CHEIOS DO ESPÍRITO',
    'O PODER DO ESPÍRITO',
    'O PODER DO ESPÍRITO',
    'ALICERCE SEGURO',
    'DÁ-ME A BÍBLIA',
    'NOVAS DE AMOR E VIDA',
    'QUE DIZ A BÍBLIA?',
    'UNIDOS PELA PALAVRA',
    'TUA PALAVRA',
    'NOSSA INSPIRAÇÃO',
    'A PALAVRA DO SENHOR',
    'O PÃO DA VIDA',
    'POR BELEZAS NATURAIS',
    'AO DEUS DE ABRAÃO LOUVAI',
    'VÓS, CRIATURAS DO SENHOR',
    'QUÃO GRANDE ÉS TU',
    'O MUNDO É DE MEU DEUS',
    'VASO NOVO',
    'DAS MÃOS DO CRIADOR',
    'NÃO HÁ OUTRO IGUAL A VOCÊ',
    'RESTAURA EM MIM',
    'RESTAURA',
    'OBRIGADO, BOM PAI',
    'A REAL BANDEIRA',
    'VITÓRIA EM CRISTO',
    'FIRME NAS PROMESSAS',
    'CASTELO FORTE',
    'GRANDE COMANDANTE',
    'FÉ É A VITÓRIA',
    'VENCEDOR CADA DIA',
    'Ó CRISTÃOS, AVANTE!',
    'UM VENCEDOR',
    'NOITE DE PAZ',
    'SOOU EM MEIO À NOITE AZUL',
    'SURGEM ANJOS PROCLAMANDO',
    'NUM BERÇO DE PALHA',
    'CANÇÃO DA MANJEDOURA',
    'Ó VINDE, ADOREMOS',
    'ESTRELA DE LUZ',
    'NASCE JESUS',
    'BELÉM, BENDITA ÉS',
    'CRISTO NASCEU',
    'NATAL, FELIZ NATAL!',
    'GLÓRIA AO REI QUE VOS NASCEU',
    'Ó NOITE SANTA',
    'ONDE ESTAVAM?',
    'NASCEU O SALVADOR',
    'VESTIDO EM LINHO',
    'AMOR, QUE POR AMOR DESCESTE',
    'FOI AMOR',
    'POR QUE ME AMOU ASSIM?',
    'CONTA-ME A HISTÓRIA DE CRISTO',
    'CONTA-ME A VELHA HISTÓRIA',
    'A DOCE HISTÓRIA',
    'SEU MARAVILHOSO OLHAR',
    'Ó VEM, EMANUEL!',
    'RUDE CRUZ',
    'NA SENDA DO CALVÁRIO',
    'OH, FRONTE ENSANGUENTADA!',
    'CRISTO NO HORTO',
    'NA CRUZ MORRI POR TI',
    'FOI POR VOCÊ TAMBÉM',
    'HOUVE ALGUÉM',
    'MONTE DO CALVÁRIO',
    'AO VER A CRUZ',
    'CORDEIRO DE DEUS',
    'STAVAS LÁ?',
    'CRISTO JÁ RESSUSSITOU',
    'PRECIOSA GRAÇA',
    'MARAVILHOSA GRAÇA',
    'INFINITA GRAÇA',
    'IMENSO AMOR',
    'GRAÇA DE DEUS',
    'GRAÇA',
    'POR UM PECADOR QUAL EU',
    'SÓ UM PASSO',
    'SEU SANGUE TEM PODER',
    'DEIXA A LUZ DO CÉU ENTRAR',
    'A TERNA VOZ DO SALVADOR',
    'FOGE PARA O MONTE',
    'VIDA EM OLHAR',
    'SE TU BUSCARES A JESUS',
    'DEIXA ENTRAR O REI DA GLÓRIA',
    'JESUS ESTÁ ESPERANDO',
    'MANSO E SUAVE',
    'PRA QUEM NADA TEM',
    'Ó VEM, AFLITO CORAÇÃO',
    'JUNTO À CRUZ',
    'VINDE ÀS ÁGUAS',
    'QUERO ESTAR AO PÉ DA CRUZ',
    'PAI, EU ME ACHEGO A TI',
    'TAL QUAL ESTOU',
    'SOU DE JESUS AGORA',
    'AO PÉ DA CRUZ DE CRISTO',
    'CRISTO TOCOU-ME',
    'PERDÃO, PODER E PAZ',
    'AO OLHAR PRA CRUZ',
    'FOI NA CRUZ',
    'É JESUS O SALVADOR',
    'EU NÃO SOU MAIS EU',
    'JESUS ME TRANSFORMOU',
    'JESUS ACHOU-ME',
    'PEDRAS',
    'Ó JESUS, HABITA EM MIM',
    'AMOR GLORIOSO',
    'A VOZ DE JESUS',
    'O QUE PENSO DE MEU MESTRE',
    'ALVO MAIS QUE A NEVE',
    'MEU CÁLICE TRANSBORDA',
    'REMIDO',
    'JESUS ME REMIU',
    'CREIO EM MILAGRES',
    'UM NOVO NOME LÁ NA GLÓRIA',
    'CREÇENDO EM GRAÇA',
    'SALVA-ME TAMBÉM',
    'SOU DE JESUS',
    'PARA O CÉU POR JESUS IREI',
    'MEU NOME EM SUAS MÃOS',
    'HOJE SOU FELIZ',
    'CAMINHANDO',
    'TÃO TRISTE EU ANDAVA',
    'EU ACHEI',
    'SALVO EM JESUS',
    'OH, QUE BELO HINO DEUS ME DEU!',
    'COM CRISTO NO MEU CORAÇÃO',
    'ANDO SEMPRE ALEGRE',
    'QUE PRAZER É SER DE CRISTO',
    'QUE CONSOLO E PAZ!',
    'DE TI CAREÇO, Ó DEUS',
    'NUNCA DESANIMES',
    'CONDUZE-ME, MEU MESTRE',
    'DEUS CUIDARÁ DE TI',
    'EU SEI EM QUEM EU CREIO',
    'NUNCA TE DEIXAREI',
    'CUIDARÁ DE MIM TAMBÉM',
    'EU PERTENÇO AO MEU REI',
    'OH, NÃO TEMAS, SOU CONTIGO',
    'QUERO TER JESUS COMIGO',
    'CADA MOMENTO',
    'Ó MESTRE, O MAR SE REVOLTA',
    'REFÚGIO EM TEMPORAL',
    'MINHA ESPERANÇA',
    'DEUS SABE, DEUS OUVE, DEUS VÊ',
    'PERTENÇO A CRISTO',
    'OLHA COM FÉ PARA CIMA',
    'BRILHO CELESTE',
    'SOB SUAS ASAS',
    'TEM FÉ EM DEUS',
    'MINHA FÉ BEM SEGURA ESTÁ',
    'AO JESUS ME TOMAR A MÃO',
    'SOU FELIZ COM JESUS',
    'DEUS VOS GUARDE',
    'AO PASSARES PELAS ÁGUAS',
    'NUNCA ME DEIXAR',
    'DIA A DIA',
    'NÃO ANDO SÓ',
    'ABRIGO NA ROCHA',
    'MEU DIVINO PROTETOR',
    'ERGO OS MEUS OLHOS',
    'FIXA TEUS OLHOS NO MESTRE',
    'CONFIEI NO MEU SENHOR',
    'CONFIA EM DEUS',
    'TODAS AS COISAS CONTRIBUEM',
    'SEMPRE CONFIANTE',
    'JESUS MEU GUIA É',
    'BENDITA SEGURANÇA',
    'NÃO ME ESQUECI DE TI',
    'NÃO HÁ O QUE TEMER',
    'A ÚNICA SAÍDA',
    'PODE CAIR O MUNDO',
    '217 sem titulo',
    'OUVE-NOS, PASTOR DIVINO',
    'DA IGREJA O FUNDAMENTO',
    'FORTALECE TUA IGREJA',
    'SOMOS IGREJA',
    'SOMOS UM PEQUENO POVO',
    'HÁ UM DEVER',
    'MENSAGEM AO MUNDO',
    'DAI-NOS LUZ',
    'CRISTO NOS CONCLAMA',
    'SE CRISTO FOR COMIGO',
    'ONDE QUER QUE SEJA',
    'TRABALHO CRISTÃO',
    'AO MUNDO VOU CONTAR',
    'TRABALHAR E ORAR',
    'JESUS PRECISA DE TI',
    'BRILHA POR CRISTO EM TEU VIVER',
    'HOJE AJUDA A ALGUÉM',
    'SOMOS TEUS, SENHOR',
    'TRANSBORDANDO EM AMOR',
    'A COLHEITA',
    'ORAÇÃO PELA MISSÃO',
    'GERAÇÃO ESPERANÇA',
    'BRILHAR POR TI',
    'A TODO SEMELHANTE MEU',
    'BENDITOS LAÇOS',
    'JESUS, PASTOR AMADO',
    'Ó VEM À IGREJA COMIGO',
    'LADO A LADO',
    'EM FAMÍLIA',
    'UNIDOS EM CRISTO',
    'ENCONTROS',
    'OH, QUE BELOS HINOS!',
    'A JESUS SEGUIR EU QUERO',
    'MEU JESUS ESTÁ CHAMANDO',
    'VOLTO AO LAR',
    'IMPORTA RENASCER',
    'AGORA POSSO VER',
    'AS ÁGUAS BATISMAIS',
    'A CEIA DO SENHOR',
    'SENHOR, TU NOS CONVIDAS',
    'A ÚLTIMA CEIA',
    'EM MEMÓRIA DE TI',
    'EM MEMÓRIA DE MIM',
    'QUEM SE DISPÕE A IR?',
    'IREI AONDE JESUS MANDAR',
    'MÃOS',
    'ENVIO A TI',
    'FAZ-ME UM SERVO',
    'NO SERVIÇO DO MEU REI',
    'AS SEARAS MADURAS',
    'COMPENSA SERVIR A JESUS',
    'SAL DA TERRA',
    'VASO DE BÊNÇÃO',
    'VASO DE HONRA',
    'ATRAVÉS DE NÓS',
    'A ESCOLA SABATINA',
    'O ENCONTRO',
    'HINO DOS AVENTUREIROS',
    'HINO DOS DESBRAVADORES',
    'BEM-AVENTURANÇA',
    'A VOZ DE DEUS',
    'A VERDADE BRILHARÁ',
    'O ESPÍRITO DE PROFECIA',
    'FILHOS DA PROMESSA',
    'EM SUA PRESENÇA',
    'CRER E OBSERVAR',
    'OBEDECER É MELHOR',
    'EU AMO A TUA LEI',
    'TUA LEI',
    'A LEI DE DEUS',
    'FIEL A TODA PROVA',
    'A TUA LEI',
    'DO SANTO SÁBADO ÉS SENHOR',
    'SÁBADO DO MEU SENHOR',
    'SÁBADO',
    'O SÁBADO CHEGOU',
    'LEMBRE-SE DO SÁBADO',
    'SÁBADO BENDITO',
    'BEM-VINDO O SÁBADO',
    'DIA DE ESPERANÇA',
    'DEUS FEZ O SÁBADO PARA MIM',
    'DIA SANTO',
    'TEMPO DE SER SANTO',
    'TOMA, Ó DEUS, MEU CORAÇÃO',
    'TUDO ENTREGAREI',
    'MINHA ENTREGA',
    'QUE TE DAREI, MEU MESTRE',
    'SOBRE O ALTAR',
    'EIS-NOS PRONTOS',
    'CONTA AS BÊNÇÃOS',
    'FAZE COMO DANIEL',
    'EM TUAS MÃOS',
    'ENTREGA',
    'INTEIRAMENTE FIEL',
    'NAS TUAS MÃOS',
    'TUDO PARA DEUS',
    'SE ELE NÃO FOR O PRIMEIRO',
    'A CRISTO EU AMO',
    'ACHEI UM GRANDE AMIGO',
    'AMIGO MUI PRECIOSO',
    'CANTAREI DE MEU JESUS',
    'CRISTO É TUDO PARA MIM',
    'EU TE AMO, MEU MESTRE',
    'JESUS É MELHOR',
    'JESUS ME GUIA',
    'HÁ UM AMIGO',
    'JESUS, TEU NOME SATISFAZ',
    'JUNTO AO BONDOSO DEUS',
    'MANANCIAL DE TODA BÊNÇÃO',
    'NÃO HÁ AMIGO IGUAL A CRISTO',
    'MEU DEUS E EU',
    'NÃO HÁ NOME MAIS AMÁVEL',
    'O MELHOR AMIGO',
    'NOME PRECIOSO',
    'TUDO ÉS PRA MIM',
    'OH, QUE AMIGO EM CRISTO TEMOS!',
    'OH, EU AMO A CRISTO!',
    'PRECIOSO É JESUS PARA MIM',
    'SALMO DOS SALMOS',
    'AMOR NOS FAZ CONTENTES',
    'DEUS NÃO SE CANSA DE AMAR',
    'EU SOU UM POBRE PEREGRINO',
    'SOU FORASTEIRO AQUI',
    'MÁGOAS',
    'EU NÃO TE DEIXAREI',
    'MEU REFÚGIO ESTÁ NO MONTE',
    'CONFIAREI',
    'NOVO DIA CHEGARÁ',
    'COMO AGRADECER',
    'OBRIGADO',
    'GRAÇAS',
    'GRATIDÃO',
    'SENHOR JESUS, MUITO OBRIGADO',
    'JESUS, MUITO OBRIGADO',
    'LUZ BENDITA, LUZ GLORIOSA',
    'É PRAZER SERVIR A CRISTO',
    'PAZ',
    'SEMPRE ALEGRE',
    'TENHO UM HINO EM MEU CORAÇÃO',
    'BENDITA HORA DE ORAÇÃO',
    'SÓ, COM TEU DEUS',
    'LUGAR DE PAZ',
    'DEUS OUVE, DEUS RESPONDE',
    'DEUS NOS OUVIRÁ',
    'O MELHOR LUGAR DO MUNDO',
    'O JARDIM DE ORAÇÃO',
    'QUE TEMPO JÁ FAZ',
    'SANTA HORA DE ORAÇÃO',
    'NO JARDIM',
    'FALAR COM DEUS',
    'AO TEU LADO QUERO ANDAR',
    'SEGUINDO A JESUS',
    'BEM JUNTO A CRISTO',
    'CADA VEZ MAIS PURO',
    'ABRE, SENHOR, OS OLHOS MEUS',
    'DEIXA-ME CONTIGO ANDAR',
    'CONTIGO, Ó DEUS, ALMEJO ANDAR',
    'CANÇÃO DA VIDA',
    'CRISTO, DÁ NOS TUA PAZ',
    'MAIS DE CRISTO',
    'MAIS PERTO QUERO ESTAR',
    'FALA À MINHA ALMA',
    'SONDA-ME, Ó DEUS',
    'TEU DIVINAL AMOR',
    'MINHA ORAÇÃO',
    'EM MIM VEM HABITAR',
    'O TEU QUERER',
    'MÚSICA CELESTE',
    'ABRE MEUS OLHOS',
    'JESUS, NÃO EU',
    'SÊ MINHA VIDA',
    'MINHA CRUZ',
    'PEGADAS',
    'QUEREMOS DAR LOUVOR',
    'SER IGUAL A CRISTO',
    'VEM COMIGO HABITAR',
    'DE HOJE EM DIANTE',
    'VEM BRILHAR',
    'VEM BRILHAR EM MIM',
    'EU SÓ QUERO ESTAR ONDE ETÁS',
    'PAI, VIVE EM MIM',
    'O CÉU É JESUS',
    'MAIS SEMELHANTE A JESUS',
    'QUERO TER JESUS',
    'PERTO DE JESUS',
    'RENOVA-ME',
    'SEMPRE DE JESUS',
    'VEM, Ó SENHOR',
    'PÉS NA TERRA, OLHOS NO CÉU',
    'O PODER DO AMOR',
    'ABENÇOA ESTE LAR',
    'AMOR NO LAR',
    'VEM ENTRE NÓS MORAR',
    'BEM DE MANHÃ',
    'BEM CEDINHO SEMPRE BUSCO',
    'VIGIAR E ORAR',
    'DESPONTA O SOL',
    'LUZES DA AURORA',
    'SURGE A ALVORADA',
    'PERTO DO LAR',
    'FINDA O DIA',
    'PRECE VESPERTINA',
    'HORA FELIZ DO PÔR DO SOL',
    'ORAÇÃO PARA UMA CRIANÇA',
    'PRESENTE DE VALOR',
    'NÃO OS IMPEÇAIS',
    'CANÇÃO PARA MEU BEBÊ',
    'OUÇO O CLAMOR DO BOM PASTOR',
    'CRISTO AMA AS CRIANCINHAS',
    'VENHAM, CRIANÇAS',
    'JOIAS PRECIOSAS',
    'QUANDO O LIVRO ABERTO FOR',
    'O JUÍZO',
    'VEM O GRANDE DIA',
    'SANGUE PRECIOSO DE CRISTO',
    'SUMO SACERDOTE',
    'SANTUÁRIO',
    'ACIMA DO CÉU',
    'E ME FAREIS UM SANTUÁRIO',
    'CHEGOU A HORA',
    'QUANDO FOR CHAMADO',
    'QUANDO DEUS FIZER CHAMADA',
    'BREVE JESUS VOLTARÁ',
    'VENCENDO VEM JESUS',
    'JESUS VOLTARÁ',
    'CRISTO VIRÁ OUTRA VEZ',
    'OH, QUE ESPERANÇA!',
    'O REI JÁ PERTO ESTÁ',
    'CRISTO VEM',
    'VIGIAI, CRISTÃOS',
    'NÓS O VEREMOS',
    'QUANDO O REI VIER',
    'GUARDA, VÊ SE MUITO FALTA',
    'GRANDE ALEGRIA',
    'CRISTO NÃO TARDA A VOLTAR',
    'ANUNCIAI PELAS MONTANHAS',
    'A MANHÃ GLORIOSA',
    'VEREI JESUS',
    'BELA MANHÃ',
    'JESUS VEM LOGO',
    'NÃO TARDARÁ',
    'CADA DIA MAIS PERTO',
    'DECIDI OLHAR PARA O AMANHÃ',
    'JESUS PRECISA VOLTAR',
    'SERÁ DE MANHÃ?',
    'ESPERO A MANHÃ GLORIOSA',
    'NÃO DESISTIR',
    'O DIA NÃO SEI',
    'UM POUCO MAIS',
    'ATÉ QUANDO?',
    'QUASE NO LAR',
    'ENQUANTO ELE NÃO VEM',
    'ROCHA ETERNA',
    'PORQUE ELE VIVE',
    'Ó ALEGRAI-VOS, FILHOS DE SIÃO',
    'MORTE E RESSURREIÇÃO',
    'EU ESPERO',
    'SE NÃO HOUVER AMANHÃ',
    'HEI DE VER',
    'FACE A FACE',
    'SIM, GLÓRIA HAVERÁ NO FINAL',
    'HERDEIRO DO REI',
    'O ETERNO LAR',
    'NO CELESTE LAR GLORIOSO',
    'JUNTO AO RIO JORDÃO',
    'VAMOS VER JESUS ALI',
    'ALÉM DO CÉU AZUL',
    'ESTRELAS TEREI',
    'ATÉ ENTÃO',
    'PRIMEIRO QUERO VER MEU SALVADOR',
    'EU VOU PARA O CÉU',
    'CRISTO FOI PREPARAR UM LUGAR',
    'TÃO GRATO ME É LEMBRAR',
    'HÁ UM RIO CRISTALINO',
    'LAR FELIZ',
    'ALMEJO O LAR',
    'DOCE LAR',
    'GLÓRIA PERENE',
    'ALÉM DO RIO',
    'INDA É LONGE CANAÃ?',
    'LINDO PAÍS',
    'MANSÃO SOBRE O MONTE',
    'OH, NUNCA SEPARAR!',
    'PARA ALÉM DAS MONTANHAS',
    'SAUDADE',
    'VALE DO ÉDEN FORMOSO',
    'MAIS PERTO DESSE LAR',
    'MUITO ALÉM DO SOL',
    'EU NÃO PRECISO MAIS SONHAR',
    'JAMAIS SE DIZ ADEUS ALI',
    'CRISTO FEZ TUDO MUITO BOM',
    'A CRIAÇÃO',
    'AQUARELA DO SENHOR',
    'EU SOU UMA OBRA DE ARTE',
    'CADA DIA',
    'VER JESUS EM VOCÊ',
    'FRUTO DA CRIAÇÃO',
    'SABE QUANTAS ESTRELINHAS?',
    'GRANDE ARTISTA',
    'MEU DEUS É TÃO GRANDE',
    'O DIA EM QUE DEUS CRIOU O MUNDO',
    'O AMIGO DO CORAÇÃO',
    'CRISTO É O NÚMERO UM',
    'O ESPÍRITO SANTO',
    'EU QUERO ESSE PODER',
    'SIM, CRISTO ME AMA',
    'JESUS ME QUER BEM',
    'DEUS SEMPRE ME AMA',
    'QUEM OROU TRÊS VEZES?',
    'ONDE QUER QUE EU VÁ',
    'QUANDO ESTOU COM MEDO',
    'SE DEUS É POR NÓS',
    'LÂMPADA PARA OS MEUS PÉS',
    'A BÍBLIA',
    'LOUVEM A JESUS',
    'LOUVAI-O',
    'EU DIGO NÃO',
    'SANTA LEI DE DEUS',
    'SÃO DEZ OS MANDAMENTOS',
    'SÁBADO, O DIA MAIS FELIZ',
    'DIA ESPECIAL',
    'DEUS MANDOU O SOL BRILHAR',
    'QUERO BEM ALEGRE OBEDECER',
    'CRIA EM MIM, Ó DEUS',
    'VEM, Ó JESUS',
    'É BOM TER JESUS NO CORAÇÃO',
    'ENTREGA TEU CAMINHO AO SENHOR',
    'SOU FELIZ',
    'QUERO SERVIR A JESUS',
    'EU SEI POR QUE NASCI',
    'O MILAGRE DA VIDA',
    'EU SOU IMPORTANTE',
    'DEUS TEM UM PLANO PRA MIM',
    'MINHA PEQUENINA LUZ',
    'MEUS TALENTOS VOU USAR',
    'MINHA VIDA É UMA VIAGEM',
    'SOU AVENTUREIRO',
    'UM LUGAR FELIZ É O CÉU',
    'LÁ NO CÉU',
    'O CÉU',
    'O SENHOR ESTÁ EM SEU TEMPLO',
    'SINTO A PRESENÇA DO SENHOR',
    'A GLÓRIA DA TUA PRESENÇA',
    'SANTO SOMENTE É O SENHOR',
    'SANTO ÉS, SENHOR',
    'SUA GLÓRIA',
    'VAMOS ADORAR',
    'ADORAÇÃO',
    'OH, ADORAI',
    'INTROITO',
    'INVOCAÇÃO',
    'NOSSO MARAVILHOSO DEUS',
    'MARAVILHOSO DEUS',
    'TU ÉS DIGNO',
    'OFERTÓRIO',
    'VENHO TE ADORAR',
    'TEU É NOSSO CORAÇÃO',
    'ENTREGO A TI',
    'HUMILDADE E GRATIDÃO',
    'QUERO ME ENTREGAR',
    'HUMILDE ORAÇÃO',
    'AO ORARMOS, SENHOR',
    'ORAÇÃO DE SÚPLICA',
    'OUVE-NOS, SENHOR',
    'PAI, VENHO A TI',
    'ENTREGAMOS EM TUAS MÃOS',
    'PRECE DE GRATIDÃO',
    'VEM, ESPÍRITO SANTO',
    'VENHAM TODOS',
    'CHEGOU A HORA DE ADORAR AO SENHOR',
    'DEIXAI VIR A MIM OS PEQUENINOS',
    'FALA, SENHOR',
    'QUEREMOS TE PEDIR, SENHOR',
    'ESTEJAS CONOSCO',
    'GRAÇA, AMOR E COMUNHÃO',
    'AMIGO, NÃO SAIA SEM CRISTO',
    'BÊNÇÃO FINAL',
    'A BÊNÇÃO',
    'VEM, SENHOR',
    'SANTO LUGAR',
    'QUE DEUS TE ABENÇOE!',
    'QUE O SENHOR NOS ABENÇOE!',
    'EM PAZ EU VOU',
  ];
  List<String> listaMapHinosComple = [
    'Santo, santo, santo! Deus onipotente!\nCedo de manhã cantaremos Teu louvor\nSanto, santo, santo! Deus Jeová triúno!\nÉs Deus excelso nosso Criador\n\nSanto, santo, santo! Nós, os pecadores\nNão podemos ver Tua glória sem tremor\nTu somente és santo justo e compassivo\nPuro e perfeito nosso Redentor\n\nSanto, santo, santo! Deus onipotente!\nTua criação manifesta o Teu amor\nAntes de criares todo o Céu e a Terra\nEras e sempre hás de ser, Senhor\n',
    'Ó adorai o Senhor na beleza\nDa santidade da glória e poder\nVinde e prostrai-vos à Sua grandeza\nEle é o princípio e sempre há de ser\nVinde a Seus pés Ele é caridade\nGrande e piedoso tardio em furor\nVinde adorá-Lo por Sua bondade\nPela grandeza do Seu santo amor\nEle criou o Universo e a Terra\nVinde e adorai-O com fé e oração\nLímpida fonte de bênçãos encerra\nFonte de graça e de redenção\n',
    'O Deus eterno reina no monte de Sião\nChegai-vos ante o trono Seu em santa adoração\nTrazei humildemente o vosso coração\nAo Deus eterno e Rei dos reis, Senhor da redenção\nO Deus eterno reina no monte de Sião\nOs astros na amplidão sem fim sustenta com a mão\nA Ele toda a honra, a glória e o poder!\nE ascendam os louvores mil ao mais sublime Ser\nO Deus eterno reina no monte de Sião\nEntrai no santo templo Seu, buscai o Seu perdão\nBuscando sua face, a paz encontrareis\nE reine para sempre, enfim, o eterno Rei dos reis\n',
    'Ó anjos e homens, dai a Deus louvores\nPois Sua graça dá aos pecadores!\nÓ firmamento, Céus e mar e Terra\nSim, dai louvor a Deus!\nVós, ó remidos, dai louvor a Cristo!\nTal sacrifício, oh, jamais foi visto!\nA Sua morte Seu amor revela\nSim, adorai Jesus!\nQuão insondável é o amor divino!\nO Santo Espírito ilumina o mundo\nÉ tão sublime, luz ao peregrino\nLuz que ao Céu conduz\n',
    'Jubilosos Te adoramos, Deus da glória, Deus do amor\nNosso coração transborda em louvor a Ti, Senhor\nRompe as nuvens da tristeza, do pecado e do temor\nDoador da eterna graça, enche-nos do Teu amor!\nTuas obras anunciam Teu poder e resplendor\nCéus e Terra cantam hinos em louvor a Ti, Senhor\nVales, montes e campinas, lindos prados, verde mar\nAves, fontes cristalinas, todos querem Te adorar!\nAleluia, aleluia, a Jesus, o Redentor!\nAleluia eternamente em louvor a Ti, Senhor\nAo Consolador dai glória, pois conforto e vida traz\nAleluia ao Pai eterno, Deus da graça, Deus da paz!\n',
    'Nós Te adoramos, Deus infinito\nE a Teu Filho, Rei, Salvador\nTeu nome eterno é sempre bendito\nTeu Espírito traz-nos amor\nGlória rendemos, honra, louvor\nE adoração a Ti, ó Senhor!\nÉramos presos pelo pecado\nTu nos livraste dessa prisão\nE, por Teu Filho imaculado\nOfertaste-nos a salvação\nGlória rendemos, honra, louvor\nE adoração a Ti, Redentor!\nTu nos convences dos vis pecados\nE da justiça, luzes nos dás\nE à verdade somos guiados\nÓ Espírito Santo de paz\nGlória rendemos, honra, louvor\nE adoração ó, Consolador!\n',
    'Sejas louvado, Rei, criador da natura!\nLouva, minh alma, louva com zelo e ternura\nLouva o Senhor, pelo insondável amor\nCálido amor que perdura!\nSejas louvado, Tu que o Universo conduzes!\nSob tuas asas, paz e conforto produzes\nHaja louvor pelo Teu dom redentor\nPríncipe eterno das luzes!\nSejas louvado, pelo cuidado paterno!\nSobre a verdade ergues Teu reino eterno\nTeu o louvor seja somente, Senhor\nPor Teu amor sempiterno!\n',
    'Ó Deus de amor, vimos nós Te adorar\nVós, ó nações, rendei louvor!\nÉs Tu, Senhor, o poderoso Vencedor\nÉs Criador e Rei sem-par\nPor Teu poder nos criaste, Senhor\nDeste-nos vida e perfeição\nMas, ao deixarmos o Teu plano de amor\nVeio em Jesus a salvação\nTeu é o poder e o louvor, nosso Deus\nTeu, nosso amor, fervor também\nQual rocha firme a verdade ficará\nDeus eternal, Senhor. Amém!\n',
    'Santo, santo, Pai bondoso\nSanto, santo, Deus poderoso\nEntregamos nosso coração a Ti, em devoção\nPai bondoso, Te adoramos\nSanto, santo, Cristo amado\nPela cruz nós somos redimidos\nElevamos nossa mente, em constante adoração\nCristo amado, Te adoramos\nSanto, santo, Santo Espírito\nEnche de poder a nossa vida\nSuplicamos Tua graça, Teu auxílio e direção\nSanto Espírito, Te adoramos\n',
    '\nO Senhor está aqui!\nO Senhor está aqui!\nVinde adorá-Lo!\nVinde exaltá-Lo!\nO Senhor está aqui!\nVamos entoar louvores ao Seu nome!\nVamos exaltar as Suas maravilhas!\nToda a Terra e Céu deem o seu louvor!\nVamos adorar o grande Criador!\nO Senhor está aqui!\nO Senhor está aqui!\n Vinde adorá-Lo!\nVinde exaltá-Lo!\nO Senhor está aqui!\nNuvens e trovões, proclamem Sua glória!\nMundos e nações, inclinem-se a Ele!\nDele é o poder, Dele é o louvor!\nVamos adorar o grande Criador!\nSenhor está aqui!\nO Senhor está aqui!\n Vinde adorá-Lo!\nVinde exaltá-Lo!\nO Senhor está aqui!\n',
    '\nMaior que forças, maior que reis\nQue a natureza e tudo que Ele fez\nMaior que coisas que o homem inventar\nNo princípio Deus estava lá\nMaior que reinos e posições\nQue as maravilhas de todas as nações\nMaior que bens e o ouro que existir\nSeu amor não pode se medir\nMas na cruz, por amor de mim\nMorreu Jesus, sozinho até o fim\nMesmo assim, em humilhação\nMorrendo só, pensando em mim\nFoi maior\nque forças, maior que reis\nQue a natureza e tudo que Ele fez\nMaior que coisas que o homem inventar\nNo princípio Deus estava lá\nMaior que reinos e posições\nQue as maravilhas de todas as nações\nMaior que bens e o ouro que existir\nSeu amor não pode se medir\nMas na cruz, por amor de mim\nMorreu Jesus, sozinho até o fim\nMesmo assim, em humilhação\nMorrendo só, pensando em mim\nFoi maior\n',
    'Vinde, povo do Senhor, adorai-O com louvor!\nAo Deus trino exaltai: a Jesus, a Deus, o Pai\nE ao Espírito de luz que em bondade nos conduz!\nVinde, povo do Senhor, adorai o Deus de amor!\n\nObservemos com fervor este dia do Senhor\nPois as bênçãos lá do Céu aos fiéis as prometeu!\nAtentai à Sua voz com amor falar a nós!\nVinde, povo do Senhor, exaltai o Criador!\n\nQuando a igreja se tornar triunfante lá no lar\nNossas lutas findarão, e virá a redenção\nMal e dor ficando atrás, reinarão amor e paz\nVinde, povo do Senhor, aclamai o Redentor!\n',
    'Louvamos-Te, ó Deus, pelo dom de Jesus\nQue por nós, pecadores, foi morto na cruz\n\nAleluia! Toda a glória\nTe rendemos sem fim\nAleluia! Tua graça\nCelebramos. Amém\n\nLouvamos-Te, ó Deus, pelo Espírito, luz\nQue nos tira das trevas e a Cristo conduz\n\nAleluia! Toda a glória\nTe rendemos sem fim\nAleluia! Tua graça\nCelebramos. Amém\n\nÓ, vem nos encher de celeste fervor\nDe esperança e bondade, de fé, zelo e amor\n\nAleluia! Toda a glória\nTe rendemos sem fim\nAleluia! Tua graça\nCelebramos. Amém\n',
    'Louvemos o Rei, glorioso Senhor!\nOh, vamos cantar de Seu infindo amor!\nEscudo seguro é Seu grande poder\nE sempre Seus filhos está a defender\n\nFalemos de Deus, da graça sem-par\nDo grande Senhor do Céu, da Terra e mar\nQue forma a chuva, o vento e a luz\nA força dos mares o Seu poder traduz\n\nCantemos de Seu cuidado por nós\nE demos ao Pai louvor em alta voz\nLouvemos, louvemos ao bom Criador\nAmigo sincero, fiel e Redentor',
    'Tu és fiel, Senhor, ó Deus eterno!\nTeus filhos sabem que não falharás!\nNunca mudaste, Tu nunca faltaste\nTal como eras, sim, sempre serás\n\nTu és fiel, Senhor! Tu és fiel, Senhor!Dia após dia, Tuas bênçãos nos dás\nA tua mão nos sustenta e nos guarda\nSim, para sempre, ó Deus, fiel serás\n\nNuvens no azul do céu, Sol refulgente\nMontes e vales, campinas em flor\nTudo criaste na terra e nos ares\nE todos louvam-Te, fiel Senhor\n\nTu és fiel, Senhor! Tu és fiel, Senhor!\nDia após dia, Tuas bênçãos nos dás\nA tua mão nos sustenta e nos guarda\nSim, para sempre, ó Deus, fiel serás\n\nPleno perdão nos dás, que segurança!\nSempre nos guias na senda do bem\nE no porvir, oh, que doce esperança\nTu nos receberás no lar de além\n\nTu és fiel, Senhor! Tu és fiel, Senhor!\nDia após dia, Tuas bênçãos nos dás\nA tua mão nos sustenta e nos guarda\nSim, para sempre, ó Deus, fiel serás\n',
    'Sublime amor, o amor de Deus\nQue lira não traduzirá!\nMaior que o mar, maior que o céu\nJamais alguém compreenderá!\nAo pecador, em aflição\nSeu Filho Deus entregou\nAo sofredor deu Ele a mão\nE as culpas lhe perdoou\n\nSublime amor, o amor de Deus!\nOh, maravilha sem-par!\nPor esse amor, eternamente\nA Deus iremos louvar\n\nSe em tinta o mar se transformasse\nE em papel o céu também\nE a pena ágil deslizasse\nDizendo o que esse amor contém\nDaria fim ao grande mar\nAo esse amor descrever\nE o céu seria tão pequeno\nPra tal relato conter\n\nSublime amor, o amor de Deus!\nOh, maravilha sem-par!\nPor esse amor, eternamente\nA Deus iremos louvar\n\nExcelso amor, o amor de Deus\nQue nos remiu da perdição!\nEm gratidão proclamaremos\nTão grande amor e salvação\nE quando enfim no lar dos Céus\nEm paz e glória eternal\nPra sempre ali desfrutaremos\nDo grande amor divinal\n\nSublime amor, o amor de Deus!\nOh, maravilha sem-par!\nPor esse amor, eternamente\nA Deus iremos louvar\n',
    'Jamais teu coração se turbe\nNem nele haja algum temor\nPois Deus, do Céu, de ti bem cuida\nOh, confia em teu Senhor!\n\nDeus é nosso Pai amado\nQue das aves cuida bem\nDá ao lírio tanta glória\nSim, te atenderá também\n\nO fardo pode ser pesado\nGrande a cruz a carregar\nLevando a Cristo teu cuidado\nEle vai te aliviar\n\nDeus é nosso Pai amado\nQue das aves cuida bem\nDá ao lírio tanta glória\nSim, te atenderá também\n\nNo céu, se negras nuvens pairam\nDando a ti perturbação\nOh, busca em Cristo novo alento!\nNele há consolação\n\nDeus é nosso Pai amado\nQue das aves cuida bem\nDá ao lírio tanta glória\nSim, te atenderá também\n',
    'Deus é nosso Pai celeste\nSomos sempre bem guardados\nNem às aves e às estrelas/nEle mostra tais cuidados\n\nDeus, com zelo, com ternura\nSeus filhinhos alimenta\nDo pecado Ele os livra\nE em Seus braços os sustenta\n\nNa tristeza ou na alegria\nNunca os filhos Deus esquece\nSeu desejo é levá-los\nPara o santo lar celeste\n\n',
    'A Deus demos glória com grande fervor\nSeu Filho bendito por nós todos deu\nA graça concede ao mais vil pecador\nAbrindo-lhe a porta de entrada no Céu\n\nExultai! Exultai! Vinde todos louvar\nA Jesus, Salvador, a Jesus, Redentor\nA Deus demos glória, porquanto do Céu\nSeu Filho bendito por nós todos deu\n\nOh, graça real! Foi assim que Jesus\nMorrendo, Seu sangue por nós derramou\nHerança nos Céus, com os santos em luz\nComprou-nos Jesus, pois o preço pagou\n\nExultai! Exultai! Vinde todos louvar\nA Jesus, Salvador, a Jesus, Redentor\nA Deus demos glória, porquanto do Céu\nSeu Filho bendito por nós todos deu\n\nA crer nos convida tal prova de amor\nNos merecimentos do Filho de Deus\nE quem, pois, confia no seu Salvador\nVai vê-Lo sentado na glória do Céu\n\nExultai! Exultai! Vinde todos louvar\nA Jesus, Salvador, a Jesus, Redentor\nA Deus demos glória, porquanto do Céu\nSeu Filho bendito por nós todos deu\n',
    'Grande é o Senhor, santo e justo Ele é!\nNós confiamos em Seu grande amor\nGrande é o Senhor, verdadeiro e fiel!\nSua graça provou Seu amor\n\nGrande é o Senhor\nE digno de glória!\nGrande é o Senhor\nDigno é de louvor!\nGrande é o Senhor\nErgamos a voz, ergamos a voz!\nGrande é o Senhor! Grande é o Senhor!\n\nGrande é o Senhor, santo e justo Ele é!\nNós confiamos em Seu grande amor\nGrande é o Senhor, verdadeiro e fiel!\nSua graça provou Seu amor\n\nGrande é o Senhor\nE digno de glória!\nGrande é o Senhor\nDigno é de louvor!\nGrande é o Senhor\nErgamos a voz, ergamos a voz!\nGrande é o Senhor! Grande é o Senhor!\n',
    'Eu Te amo, ó Deus; ergo meu louvor\nMinhalma vem Te adorar, Senhor\nAceita, pois, este meu louvor\nComo gratidão por Teu grande amor\n',
    'A Ti toda glória e louvores rendemos\nSenhor do Universo e Deus, Criador!\nReunidos, rogamos as Tuas santas bênçãos\nE graças ofertamos por Teu grande amor\n\nÓ Fonte perene de bênçãos constantes\nFruindo Tua graça queremos viver\nSustém-nos os passos, pois são mui vacilantes\nSomente pela fé nós podemos vencer\n\nLouvores rendemos por Tua bondade\nTeu Filho querido nos deste na cruz\nSua morte nos trouxe perdão e eternidade\nE abriu-nos os portais para o reino de luz\n',
    'Ó louvai-O: Cristo, o bom Mestre divino!\nPra salvar-nos, a Sua vida deu\nGraça e força hoje aos contritos outorga\nPois Seu sangue por todos nós verteu\nSim, louvai-O; seja pra sempre honrado!\nPor Seus filhos, um mediador será\n\nExaltai-O pelas excelsas grandezas\nDesta graça que hoje aos perdidos dá!\n\nÓ louvai-O: Cristo, o bom Mestre divino!\nBons conselhos dá Ele ao pecador\nDai ao mundo dádivas maravilhosas\nConcedidas por esse Salvador\nIde, todos servos fiéis de Cristo\nEle nunca vos abandonará\n\nExaltai-O pelas excelsas grandezas\nDesta graça que hoje aos perdidos dá!\n\nÓ louvai-O: Cristo, o bom Mestre divino!\nEntre os povos, Seu grande amor cantai\nCristo volta com os milhares de anjos\nLogo ao mundo esta mensagem dai\nCristo, o bom pastor, cuida do seu rebanho\nEle os salvos sempre conduzirá\n\nExaltai-O pelas excelsas grandezas\nDesta graça que hoje aos perdidos dá!\n',
    'Rei dos reis! Deus criador do Céu!\nHonra e glória ao Deus infinito em poder!\nTerra e Céu, cantai ao grande Rei!\nDeus criador, Deus redentor, Deus, Rei dos reis!\n\nAdorai, glorificai o nome de Cristo!\nExaltai, magnificai Jesus, o Senhor!\nTerra e Céu, cantai louvor a Deus!\nEle morreu! Ele venceu! É Rei dos reis!\n\nAdorai, glorificai o nome de Cristo!\nExaltai, magnificai Jesus, o Senhor!\nTerra e Céu, cantai louvor a Deus!\nEle morreu! Ele venceu! É Rei dos reis!\n',
    'Jesus, sempre Te amo, porque sei que és meu\nA Ti toda a glória, na Terra e no Céu!\nMeu Mestre divino, meu Deus e meu Rei\nA Ti, ó meu Cristo, submisso serei\n\nEu Te amo porque Tu morreste por mim\nEu Te amo porque Teu amor não tem fim\nEm Ti confiança pra sempre terei\nA Ti, ó meu Cristo, submisso serei\n\nEu Te amo, meu Mestre, enquanto viver\nEu hei de louvar-Te com grande prazer\nAgora e pra sempre Contigo estarei\nA Ti, ó meu Cristo,submisso serei\n',
    'Saudai o nome de Jesus\nÓ anjos, vos prostrai\nO Filho do glorioso Deus\nCom glória, coroai!\nO Filho do glorioso Deus\nCom glória, coroai!\n\nÓ escolhida geração\nDo bom e eterno Pai\nO grande Autor da salvação\nCom glória, coroai!\nO grande Autor da salvação\nCom glória, coroai!\n\nÓ perdoados por Jesus\nAlegres adorai\nO Deus de paz, o Deus de luz\nCom glória, coroai!\nO Deus de paz, o Deus de luz\nCom glória, coroai!\n\nÓ povos, tribos e nações\nAo Rei divino honrai\nA quem quebrou os vis grilhões\nCom glória, coroai!\nA quem quebrou os vis grilhões\nCom glória, coroai!\n',
    'Saudai o nome de Jesus!\nÓ anjos, vos prostrai!\nÓ anjos, vos prostrai!\nO Filho do glorioso Deus\n\nCom glória, glória, glória\nGlória, com glória, coroai!\n\nÓ escolhida geração\nDo bom e eterno Pai\nDo bom e eterno Pai\nO grande Autor da salvação\n\nCom glória, glória, glória\nGlória, com glória, coroai!\n\nÓ perdoados por Jesus\nAlegres adorai\nAlegres adorai!\nO Deus de paz, o Deus de luz\n\nCom glória, glória, glória\nGlória, com glória, coroai!\n\nÓ povos, tribos e nações\nAo Rei divino honrai\nAo Rei divino honrai!\nA quem quebrou os vis grilhões\n\nCom glória, glória, glória\nGlória, com glória, coroai!\n',
    'Lindo és, meu Mestre, Rei do Céu, da Terra!\nÓ Homem-Deus, Senhor Jesus\nTeu é o reino, é Tua a honra\nÉs minha glória e minha luz\n\nFlores do campo! Como são tão lindas!\nSão o fulgor de prados mil.\nMais belo é Cristo, mais puro e lindo\nÉ sempre meigo, bom, gentil\n\nLua brilhante, Sol tão resplendente!\nQuão divinal é sua luz!\nMas há um brilho mais fulgurante:\nO brilho do Senhor Jesus\n',
    'O amor de Jesus é tão puro e leal\nQue aclara o meu viver\nO amor de Jesus me liberta do mal\nE envolve meu pobre ser\nTão meigo e tão bom é Jesus!\nE guia-me com Sua mão\nO amor de Jesus é qual fonte de luz:\nTirou-me da escuridão\n\nO amor de Jesus é mais vasto que o mar\nSustém-me na provação\nO amor de Jesus, qual fragrância da flor\nInunda meu coração\nSua paz dá-me calma e prazer\nEu sei que há um Céu para mim\nA Cristo Jesus minha vida darei\nPor Seu grande amor sem fim\n',
    'Sempre vencendo, mui vitorioso\nCristo Jesus, o Senhor!\nChefe bendito, Chefe glorioso\nEm tudo é vencedor\nEi-Lo supremo, guiando\nCom Seu poder e valor\nTodos avante, ó crentes\nTodos seguindo o Senhor\n\nNão é dos fortes a vitória\nNem dos que correm melhor\nMas dos fiéis e sinceros\nComo nos diz o Senhor\n\nSempre vencendo, mui vitorioso\nCristo Jesus, o Senhor!\nEis Suas hostes inumeráveis\nSeu refulgente esplendor!\nCristo, que é nosso Monarca\nÉ Salvador, Deus e Pai\nSempre nos ama, nos guarda\nSempre conosco Ele vai\n\nNão é dos fortes a vitória\nNem dos que correm melhor\nMas dos fiéis e sinceros\nComo nos diz o Senhor\n\nSempre vencendo, mui vitorioso\nCristo Jesus, o Senhor!\nReis e monarcas, príncipes fortes\nBuscam também Seu favor\nHumildemente Te peço\nQue me permitas lutar\nSó ao Teu lado, seguro\nTé minha vida findar\n\nNão é dos fortes a vitória\nNem dos que correm melhor\nMas dos fiéis e sinceros\nComo nos diz o Senhor\n',
    'Jesus, Tu és a minha vida\nJesus, Tu és o meu cantar\nTu és a estrada mais bonita\nPor onde eu devo caminhar\nJesus, Tu és a primavera\nQue faz a vida florescer\nTu és a chama da alegria\nQue faz brilhar todo o meu ser\n\nJesus, Tu és a melodia\nA voz, o canto, a emoção\nTu és a força que me inspira\nA dar louvor na provação\nJesus, Tu és a esperança\nQue faz vibrar meu coração\nJesus, Tu és a energia\nQue move a vida do cristão\n\nJesus, Tu és o meu caminho\nVerdade, vida e salvação\nJesus, Tu és a minha glória\nMotivo de minha adoração\nJesus, Tu és meu Pai querido\nA quem dedico o meu viver\nTu és pra sempre a minha vida\nJesus, és vida no meu ser\n',
    'Pai, o Teu grande amor me inspira\nPai, o Teu resplendor me anima\nTua luz ilumina os caminhos meus\nComo um sol, o amor desses olhos Teus\nBrilha em mim, brilha em mim\n\nBrilha Jesus!\nVem trazer a luz que vem da glória\nO Teu calor traz a paz e amor\nVem como um sol\nÀs nações trazer misericórdia\nBrilha, Jesus! Vem trazer Tua luz\n\nPai a Tua real grandeza\nTraz à vida real beleza\nTeu amor transformou nossa história\nHoje a luz que nos vem lá da glória\nBrilha em mim, brilha em mim\n\nBrilha Jesus!\nVem trazer a luz que vem da glória\nO Teu calor traz a paz e amor\nVem como um sol\nÀs nações trazer misericórdia\nBrilha, Jesus! Vem trazer Tua luz\n',
    'Não há esperança alguma\nPra um mundo onde Deus não está\nNão há esperança de amor e de paz\nOnde o ódio deixa marcas fatais\n\nNão há esperança de vida\nNaqueles que não amam a Deus\nNão há esperança de um mundo de paz\nSe o homem deixa Deus para trás\n\nA esperança é Jesus\nEle é o caminho\nA esperança é Jesus\nNossa luz entre espinhos\nA esperança é Jesus\nSegurança de salvação\nOnde o mundo pode achar solução\nA esperança é Jesus\n\nSó há esperança e certeza\nNaquele que é vencedor\nSó há esperança no nome de Deus\nPara um povo que não tem mais amor\n\nA esperança é Jesus\nEle é o caminho\nA esperança é Jesus\nNossa luz entre espinhos\nA esperança é Jesus\nSegurança de salvação\nOnde o mundo pode achar solução\nA esperança é Jesus\n',
    'Tenho ouvido muitos nomes\nNomes que hoje vêm e logo vão\nMas existe um nome eterno\nFonte de poder e salvação\n\nPrecioso nome, o nome de Jesus\nTão belo e meigo\nSempre um grande bem produz\nMesmo quando é forte o pranto\nEsse nome traz encanto\nPrecioso nome, o nome santo, Jesus\n\nEsse nome é poderoso\nPra fazer alguém de novo amar\nQuem procura segurança\nPode nesse nome encontrar\n\nPrecioso nome, o nome de Jesus\nTão belo e meigo\nSempre um grande bem produz\nMesmo quando é forte o pranto\nEsse nome traz encanto\nPrecioso nome, o nome santo, Jesus\nPrecioso nome, o nome santo, Jesus\n',
    'Ele é exaltado, o Rei é exaltado nos Céus\nEu O louvarei\nEle é exaltado, pra sempre é exaltado\nO Seu nome louvarei\nEle é o Senhor\nSua verdade vai sempre reinar\nTerra e Céus\nGlorificam Seu santo nome\nEle é exaltado, o Rei é exaltado nos Céus\n\nEle é exaltado, o Rei é exaltado nos Céus\nEu O louvarei\nEle é exaltado, pra sempre é exaltado\nO Seu nome louvarei\n\nEle é o Senhor\nSua verdade vai sempre reinar\nTerra e Céus\nGlorificam Seu santo nome\nEle é exaltado, o Rei é exaltado nos Céus\nEle é exaltado, o Rei é exaltado nos Céus\n',
    'O Universo, em seu resplendor\nRevela um Deus Criador\n\nPor isso, exalto a Jesus, meu Senhor\nPor Seu imenso amor\nSó a Jesus, só a Jesus, exaltarei cada dia\nSó a Jesus, só a Jesus, dedicarei meu louvor\nQuero pra sempre a Cristo adorar\nPor Seu imenso amor\n\nMesmo sabendo que indigno eu sou\nEle jamais me deixou\n\nPor isso, exalto a Jesus, meu Senhor\nPor Seu imenso amor\nSó a Jesus, só a Jesus, exaltarei cada dia\nSó a Jesus, só a Jesus, dedicarei meu louvor\nQuero pra sempre a Cristo adorar\nPor Seu imenso amor\n\nA vida eterna, sem pranto e dor\nEle, por mim, conquistou\n\nPor isso, exalto a Jesus, meu Senhor\nPor Seu imenso amor\nSó a Jesus, só a Jesus, exaltarei cada dia\nSó a Jesus, só a Jesus, dedicarei meu louvor\nQuero pra sempre a Cristo adorar\nPor Seu imenso amor\n\nPor Seu imenso amor\nPor Seu imenso amor\n',
    'Cristo é amigo, Cristo é irmão\nCristo é grandioso, Cristo é união\nDele é toda a glória, Dele é o poder\nCristo é amparo, Cristo é salvação\n\nCristo é Rei da glória, Cristo é o Senhor\nCristo é abrigo, Cristo é amor\n\nCristo é meu guia, Cristo é farol\nCristo é luz que brilha, Cristo é como um sol\nDele é minha vida, Dele é o meu ser\nCristo é alegria, Cristo é canção\nCristo é Rei da glória, Cristo é o Senhor\nCristo é abrigo, Cristo é amor\n',
    'A Ti rendemos glórias, ó Rei e Redentor\nA quem crianças rendem também o seu louvor\nSenhor, nos inclinamos aos Teus sagrados pés\nE a Ti nós adoramos, pois Deus eterno és\n\nA voz dos santos anjos, em sons celestiais\nAqui na Terra ecoa na voz dos vis mortais\nSó Tu, ó Deus bondoso, és o Pastor fiel\nO Rei dos reis vindouro, Senhor de Israel\n\nLouvor Te deram antes da cruz e da paixão\nE nós também cantamos o dom da salvação\nPois Teu, Senhor, é o reino, a glória e o poder\nE a Ti, pra sempre, os salvos mui gratos hão de ser\n',
    'Glórias ao Rei de amor, ao Rei, Senhor Jesus!\nO Seu divino e santo amor provou ali na cruz\nA Cristo, o Redentor, darei louvor sem fim\nLouvor ao santo Rei de amor, que a vida deu por mim\n\nGlórias ao Rei da luz, do bem o manancial!\nLouvor ao nobre Rei da luz, ao dom celestial\nSenhor da Terra e mar, da luz que ao Céu conduz\nLouvor ao nobre Rei da luz, ao Rei que a Deus traduz\n\nGlórias ao Rei da paz, ao Rei, Senhor e Deus!\nLouvor ao grande Rei da paz, ao Rei dos altos Céus\nÓ Rei, por Teu favor, ali irei morar\nViver a eterna e doce paz, a paz do eterno lar\n"',
    'Concede-nos, ó Deus, o Espírito de amor\nE ao nosso coração, o Teu Consolador\nNo mundo atroz\nQue sempre o Santo Espírito esteja em nós!\n\nConvença o mundo então do juízo e do mal\nE da justiça, enfim, com graça divinal\nConcede, ó Deus\nQue andem na Verdade aqui os filhos Teus\n\nPermite-nos aqui louvar a Deus, o Pai\nE ao Filho em alta voz, ó povos, glória dai\nLouvai também\nO bom e Santo Espírito pra sempre. Amém!\n',
    'Chuvas de bênçãos teremos\nÉ a promessa de Deus\nTempos benditos veremos\nChuvas de bênçãos dos Céus\nSim, chuvas de bênçãos\nChuvas de bênçãos dos Céus\nGotas somente nós temos\nChuvas rogamos a Deus\n\nChuvas de bênçãos teremos\nVida de paz e perdão\nOs pecadores indignos\nGraça dos Céus obterão\n\nSim, chuvas de bênçãos\nChuvas de bênçãos dos Céus\nGotas somente nós temos\nChuvas rogamos a Deus\n\nChuvas de bênçãos teremos\nManda-nos já, ó Senhor!\nDá-nos agora o bom fruto\nDesta promessa de amor\n\nSim, chuvas de bênçãos\nChuvas de bênçãos dos Céus\nGotas somente nós temos\nChuvas rogamos a Deus\n\nChuvas de bênçãos teremos\nChuvas mandadas dos Céus\nBênçãos a todos os crentes\nBênçãos do nosso bom Deus\n\nSim, chuvas de bênçãos\nChuvas de bênçãos dos Céus\nGotas somente nós temos\nChuvas rogamos a Deus\n',
    'Vive, Santo Espírito\nNeste meu pobre ser\nFaz no meu coração a luz\nDo Céu resplandecer\n\nVive em mim, vive em mim\nSanto e bom Consolador\nLimpa do mal meu coração\nReine nele só o amor\nFala, Santo Espírito\nFala-me com poder\nPois para a redenção real\nEu quero renascer\n\nVive em mim, vive em mim\nSanto e bom Consolador\nLimpa do mal meu coração\nReine nele só o amor\n\nSanto, Santo Espírito\nEnche-me de fervor\nPara que eu ponha o meu viver\nNas mãos do Salvador\n\nVive em mim, vive em mim\nSanto e bom Consolador\nLimpa do mal meu coração\nReine nele só o amor\n',
    'Vem, Santo Espírito, agora\nVem, Te pedimos a orar\nVem com poder inspirar-nos\nSim, vem nos reavivar\n\nVem como água ao sedento\nTraz ao faminto o pão\nVem e sacia minha alma\nFaz puro meu coração\n\nVem como a brisa suave\nVem com o Teu resplendor\nDá-nos vigor e alegria\nEnche-nos com Teu amor\n\nÓ vem, Espírito Santo\nBom, meigo Consolador\nVem inundar nossa vida\nCom Teu sagrado fervor\n',
    'O Santo Espírito desceu do Céu\nEm plenitude de poder\nE o Pentecostes fez brilhar a luz\nE multidões puderam crer\nFiéis em Cristo, sem qualquer temor\nSaíram todos a pregar\nE conseguiram, mesmo em luta e dor\nFinal vitória conquistar\n\nÓ Deus bendito, hoje também\nVem conceder-nos Tua graça e Teu poder\nEis nossa prece: Vem perto estarVem Tua Igreja aqui reavivar\n\nSó pela fé o justo vai viver"\nNa Bíblia vamos encontrar\nJesus, portanto, nos dará poder\nDevemos crer e confiar\nOs que esperam sempre no Senhor\nPaz e alegria hão de achar\nReceberão de Deus constante amor\nE graça pra testemunhar\n\nÓ Deus bendito, hoje também\nVem conceder-nos Tua graça e Teu poder\nEis nossa prece: Vem perto estar\nVem Tua Igreja aqui reavivar\n',
    'Há um suave espírito entre nós\nÉ do Espírito de Deus a doce voz\nVejo em cada rosto o resplendor\nDa presença do Espírito do Senhor\n\nÓ Santo Espírito, vindo do Céu\nFica conosco, enche-nos de fervor!\nE por tais bênçãos rendemos-Te louvor\nE assim reavivados vamos todos ser\nPor Teu poder e amor\n\nHá prazer em cada coração\nPois o Espírito desperta em nós o amor\nE nos faz viver em união\nDedicados ao serviço do Senhor\n\nÓ Santo Espírito, vindo do Céu\nFica conosco, enche-nos de fervor!\nE por tais bênçãos rendemos-Te louvor\nE assim reavivados vamos todos ser\nPor Teu poder e amor\n',
    'Hoje é o dia em que temos de pedir\nPela benção da presença do Senhor\nHoje é o dia em que temos de orar\nPela benção da presença desse amor\n\nDerrama a chuva sobre nós\nDerrama o Teu poder de amor\nTeu Espírito pedimos, ó Senhor\nDerrama a chuva sobre nós\nDerrama o Teu poder de amor\nTeu Espírito envia, ó Senhor\n\nHoje é o dia em que temos de orar\nPra que o Céu derrame bênçãos sobre nós\nHoje é o dia em que temos de falar\nQue Jesus está mais perto de voltar\n\nDerrama a chuva sobre nós\nDerrama o Teu poder de amor\nTeu Espírito pedimos, ó Senhor\nDerrama a chuva sobre nós\nDerrama o Teu poder de amor\nTeu Espírito envia, ó Senhor\n',
    'O Espírito de Deus nos guiará pela verdade\nDizendo com clareza as coisas certas que virão\nJesus em nossa vida vencerá a falsidade\nNo mundo que se perde em meio à escuridão\n\nCheios do Espírito, cheios de poder\nIremos proclamar a paz que vem da cruz\nCheios do Espírito, cheios de poder\nIremos anunciar a volta de Jesus\nCheios do Espírito, cheios de poder\n\nConfiantes na riqueza da glória de Jesus\nVivemos o poder de Seu Espírito em nós\nAssim nós proclamamos Sua graça, eterna luz\nAo mundo que tem fome de ouvir a Sua voz\n\nCheios do Espírito, cheios de poder\nIremos proclamar a paz que vem da cruz\nCheios do Espírito, cheios de poder\nIremos anunciar a volta de Jesus\nCheios do Espírito, cheios de poder\n',
    'Ao descer sobre nós\nO poder do Santo Espírito de Deus\nNosso ser, nossa voz\nCom poder proclamarão os atos Seus\nO mundo há de ouvir que Jesus irá voltar\nCom poder e grande glória irá reinar\nO Espírito de Deus através do nosso amor\nLevará a todo mundo Cristo Salvador\n\nAo descer sobre nós\nO poder do Santo Espírito de Deus\nNosso ser, nossa voz\nCom poder proclamarão os atos Seus\nO mundo há de ouvir que Jesus irá voltar\nCom poder e grande glória irá reinar\nO Espírito de Deus através do nosso amor\nLevará a todo mundo Cristo Salvador\n',
    'Que firme alicerce na Santa Escritura\nEncontram os crentes em lutas e dor!\nGrandes promessas e com tal ternura\nQuem há que as daria, senão o Senhor?\nQuem há que as daria, senão o Senhor?\n\nSe fores chamado a passar pelas águas\nProfundas e bravas de angústia e aflição\nCrê, pois contigo estarei nessas mágoas\nE em glória perene depois findarão\nEm glória perene depois findarão\n\nSe tua vereda passar pela chama\nDe fogos ardentes, não fujas à dor!\nPalha, somente, no fogo se inflama\nO ouro, na chama, duplica o valor\nO ouro, na chama, duplica o valor\n\nA todo que em Mim vem buscar o repouso\nConfiado no sangue do Filho de Deus\nEu o farei um cristão vitorioso\nPor certo estará nas moradas dos Céus!\nPor certo estará nas moradas dos Céus!\n',
    'Que firme alicerce podemos achar\nNa Santa Escritura pra a fé basear!\nSão ricas promessas pra quem nelas crer\nPra quem quer refúgio em Jesus receber\nNão temas, Meu filho, bem perto Eu estou\nPois sou o seu Deus, sempre à frente Eu vou\nEu posso ajudar e a você sustentar\n\nA mão Eu estendo e o posso amparar\nSe em águas profundas tiver que seguir\nOs rios não irão a você submergir\nSe a sua estrada o fogo cruzar\nA graça darei pra prover e cuidar\n\nQuem quer encontrar o repouso em Jesus\nTerá proteção bem à sombra da cruz\nEmbora em conflitos, em lutas ou dor\nBem perto estarei ao seu lado co’amor\n',
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        centerTitle: true,
        title: Text('${listaMapHinos[index]}',
            style: TextStyle(fontSize: 25, color: Colors.black)),
      ),


      body:

      Column(children: [

        Container(height: 50.0,
          width: 600.0,
          color: Colors.white,),
        Center(child: Container(
          height: 609.0,
          width: 500.0,
          color: Colors.black,
          child: Align(alignment: Alignment.center,
          child:  Text('${listaMapHinosComple[index]}',
            style: TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.w500,
              fontSize: 15,

            ),
          ),

          ),




        ),),

        Container(height: 20.0,
          width: 500.0,

          child: Align(alignment: Alignment.center,
            child:  Text('Assinado: Gabriel e Artur',
              style: TextStyle(
                color: Colors.black,
                fontWeight: FontWeight.w500,
                fontSize: 5,

              ),
            ),

          ),
        ),
      ],)

    );
  }
}
